name: Release
on:
  push:
    tags: v\d+
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: echo "::set-output name=branch-name::release-$($GIT_REF_NAME)"
        id: form-branch-name
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.form-branch-name.outputs.branch-name }}
    outputs:
      branch-name: ${{ steps.form-branch-name.outputs.branch-name }}

  run_tests:
    needs: create-release-branch
    uses: ./.github/workflows/run-tests.yml
    with:
      branch-name: ${{ needs.create-release-branch.outputs.branch-name }}

  create-release-issue:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: result_url
      - name: Pull url to env variable
        shell: bash
        run: echo "TEST_RESULTS=$(cat test_result_url.txt)" >> $GITHUB_ENV
      - name: Create or update release issue
        id: create-release-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          TAG_NAME: $GITHUB_REF_NAME
          ACTOR: $GITHUB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update_existing: true
          search_existing: all
      - name: Write issue id in file
        id: write-issue-id
        shell: bash
        run: |
          echo "${{ steps.create-release-issue.outputs.number }}" > $($GIT_REF_NAME).txt
          echo "::set-output name=file-name::$($GIT_REF_NAME).txt"
      - name: Save release issue id for use in other workflows
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.GITHUB_REF_NAME }}
          path: ${{ steps.write-issue-id.outputs.file-name }}
