name: Process hotfix
on:
  push:
    branches: release-v\d+
jobs:
  run-tests:
    uses: "./.github/workflows/run-tests.yml"
    with:
      branch-name: ${{ github.ref_name }}
  create-hotfix-log:
    needs: run-tests
    if: success()
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - shell: bash
        run: echo "::set-output name=release-tag::$(git describe --tags --abbrev=0)"
        id: get-release-tag
      - name: Create changelog with hotfixes
        uses: nielstenboom/semantic-changelog-generator@v1.2.0
        id: changelog
        with:
          base: ${{ steps.get-release-tag.outputs.release-tag }}
          head: ${{ github.ref_name }}
      - shell: bash
        run: |
          cat << "EOF" > changelog.txt
          ## Hotfix
          ${{ steps.changelog.outputs.changelog }}
          EOF
      - name: Find issue number
        with:
          labels: |
            release
            ${{ steps.get-release-tag.outputs.release-tag }}
          state: open
        id: get-issue-number
        uses: micalevisk/last-issue-action@v2.0.0
      - name: Create comment
        run: gh issue comment ${{ steps.get-issue-number.outputs.issue-number }} -F changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
