name: Process hotfix
on:
  push:
    branches: release-v\d+
jobs:
  run-tests:
    uses: "./.github/workflows/run-tests.yml"
    with:
      branch-name: ${{ github.ref_name }}
  create-hotfix-log:
    needs: run-tests
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: echo "::set-output name=release-tag::$(git describe --tags --abbrev=0)"
        id: get-release-tag
      - name: Create hotfix changelog
        uses: mikepenz/release-changelog-builder-action@v4.0.0-rc02
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitMode: true
          fromTag: ${{ steps.get-release-tag.outputs.release-tag }}
          toTag: ${{ github.ref_name }}
          outputFile: hotfix-changelog${{ steps.get-release-tag.outputs.release-tag }}.txt
  update-issue-with-hotfix:
    needs: create-hotfix-log
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: echo "::set-output name=release-tag::$(git describe --tags --abbrev=0)"
        id: get-release-tag
      - name: Find issue id
        with:
          labels: |
            release
          status: open
        id: get-issue-id
        uses: micalevisk/last-issue-action@v2.0.0
      - name: Create comment
        run: gh issue comment ${{ steps.get-issue-id.outputs.issue-number }} -F hotfix-changelog${{ steps.get-release-tag.outputs.release-tag }}.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
