name: Release
on:
  push:
    tags: v\d+
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  run_tests:
    uses: ./.github/workflows/run-tests.yml
  create-release-issue:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: result_url
      - name: Pull url to env variable
        shell: bash
        run: echo "TEST_RESULTS=$(cat test_result_url.txt)" >> $GITHUB_ENV
      - name: Create or update release issue
        uses: JasonEtco/create-an-issue@v2
        env:
          TAG_NAME: $GITHUB_REF_NAME
          ACTOR: $GITHUB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update_existing: true
          search_existing: all
