name: Run tests

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name || ''}}
      - uses: actions/setup-node@v3
      - name: Install deps
        run: npm ci; npx playwright install --with-deps chromium
      - name: Run tests
        run: npm run test-ci
  get-url-to-results:
    runs-on: ubuntu-latest
    steps:
      - name: Save url to .txt
        shell: bash
        run: echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" > test_result_url.txt
      - name: Create artifact with url
        uses: actions/upload-artifact@v3
        with:
          name: result_url
          path: test_result_url.txt
